[flake8]
max-line-length = 100
exclude = .git,__pycache__,.venv,venv,env,.eggs,*.egg,dist,build
ignore = E203,W503

[tool.black]
line-length = 100
skip-string-normalization = false
exclude = '''
/(\.|venv|env|dist|build|__pycache__)/
'''
